#!/usr/bin/env python

import logging, sys

from wildcatting.cmdparse import CommandParser

from wildcatting import ClientCommand
from wildcatting import ConsoleCommand
from wildcatting import ScreensaverCommand
from wildcatting import ServerCommand
from wildcatting import ThemeInfoCommand
from wildcatting import version

parser = CommandParser()
parser.add_option("", "--debug", action="store_true",
                  help="enable debugging output")
parser.add_option("", "--version", action="store_true",
                  help="print the version and exit")

parser.add_commands(ClientCommand)
parser.add_commands(ConsoleCommand)
parser.add_commands(ScreensaverCommand)
parser.add_commands(ServerCommand)
parser.add_commands(ThemeInfoCommand)

if __name__ == "__main__":
    (command, options, args) = parser.parse_args()

    formatter = logging.Formatter("%(levelname)s: %(message)s")
    console = logging.StreamHandler()
    console.setFormatter(formatter)
    logging.root.addHandler(console)

    if options.debug:
        logging.root.setLevel(logging.DEBUG)
    else:
        logging.root.setLevel(logging.ERROR)

    if options.version:
        print version.VERSION_STRING
        sys.exit(0)

    if command is None:
        parser.print_help()
        sys.exit(1)

    try:
        command.run(options, args)
    except KeyboardInterrupt:
        print
        sys.exit(1)
