#!/usr/bin/env python

import logging, sys

from wildcatting.cmdparse import CommandParser

from wildcatting import ClientCommand
from wildcatting import ScreensaverCommand

parser = CommandParser()
parser.add_option("", "--debug", action="store_true",
                  help="enable debugging output")

parser.add_commands(ClientCommand)
parser.add_commands(ScreensaverCommand)

if __name__ == "__main__":
    (command, options, args) = parser.parse_args()

    formatter = logging.Formatter("%(levelname)s: %(message)s")
    console = logging.StreamHandler()
    console.setFormatter(formatter)
    logging.root.addHandler(console)

    if options.debug:
        logging.root.setLevel(logging.DEBUG)
    else:
        logging.root.setLevel(logging.ERROR)

    if command is None:
        parser.print_help()
        parser.exit()
    
    try:
        command.run(options, args)
    except KeyboardInterrupt:
        sys.exit(1)
